import { TerminalTheme } from '../types';

export interface ThemeConfig {
  id: TerminalTheme;
  name: string;
  badge: string;
  bg: string;
  bgSecondary: string;
  text: string;
  textMuted: string;
  textBright: string;
  border: string;
  borderActive: string;
  accent: string;
  accentBg: string;
  verseNum: string;
  bloomClass: string;
  cursorColor: string;
  promptUser: string;
  promptHost: string;
}

export const THEMES: Record<TerminalTheme, ThemeConfig> = {
  matrix: {
    id: 'matrix',
    name: 'Matrix Phosphor',
    badge: 'CRT-GREEN',
    bg: 'bg-[#030904]',
    bgSecondary: 'bg-[#08170c]',
    text: 'text-green-400',
    textMuted: 'text-green-700',
    textBright: 'text-green-200',
    border: 'border-green-900',
    borderActive: 'border-green-500',
    accent: 'text-emerald-300',
    accentBg: 'bg-green-950/80',
    verseNum: 'text-green-500 font-bold',
    bloomClass: 'crt-bloom-green',
    cursorColor: 'bg-green-400',
    promptUser: 'text-green-300',
    promptHost: 'text-green-600',
  },
  amber: {
    id: 'amber',
    name: 'Vintage Amber 1982',
    badge: 'CRT-AMBER',
    bg: 'bg-[#0f0800]',
    bgSecondary: 'bg-[#1e1002]',
    text: 'text-amber-400',
    textMuted: 'text-amber-700',
    textBright: 'text-amber-200',
    border: 'border-amber-900',
    borderActive: 'border-amber-500',
    accent: 'text-amber-300',
    accentBg: 'bg-amber-950/80',
    verseNum: 'text-amber-500 font-bold',
    bloomClass: 'crt-bloom-amber',
    cursorColor: 'bg-amber-400',
    promptUser: 'text-amber-300',
    promptHost: 'text-amber-600',
  },
  nord: {
    id: 'nord',
    name: 'Nordic Arctic CLI',
    badge: 'NORD-ICE',
    bg: 'bg-[#181c24]',
    bgSecondary: 'bg-[#222834]',
    text: 'text-cyan-200',
    textMuted: 'text-slate-500',
    textBright: 'text-white',
    border: 'border-slate-800',
    borderActive: 'border-cyan-500',
    accent: 'text-cyan-300',
    accentBg: 'bg-cyan-950/60',
    verseNum: 'text-cyan-400 font-bold',
    bloomClass: 'crt-bloom-cyan',
    cursorColor: 'bg-cyan-300',
    promptUser: 'text-cyan-300',
    promptHost: 'text-slate-400',
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    badge: 'CYBER-NEON',
    bg: 'bg-[#0a0514]',
    bgSecondary: 'bg-[#150a2a]',
    text: 'text-cyan-300',
    textMuted: 'text-purple-500',
    textBright: 'text-pink-300',
    border: 'border-fuchsia-900',
    borderActive: 'border-cyan-400',
    accent: 'text-fuchsia-400',
    accentBg: 'bg-fuchsia-950/60',
    verseNum: 'text-pink-400 font-bold',
    bloomClass: 'crt-bloom-cyan',
    cursorColor: 'bg-pink-400',
    promptUser: 'text-fuchsia-400',
    promptHost: 'text-cyan-400',
  },
  dos: {
    id: 'dos',
    name: 'Classic DOS / VGA',
    badge: 'VGA-DOS',
    bg: 'bg-[#000080]',
    bgSecondary: 'bg-[#0000a8]',
    text: 'text-gray-100',
    textMuted: 'text-gray-400',
    textBright: 'text-yellow-300',
    border: 'border-blue-400',
    borderActive: 'border-white',
    accent: 'text-yellow-300',
    accentBg: 'bg-blue-900/80',
    verseNum: 'text-cyan-300 font-bold',
    bloomClass: '',
    cursorColor: 'bg-gray-100',
    promptUser: 'text-yellow-300',
    promptHost: 'text-cyan-300',
  },
  paper: {
    id: 'paper',
    name: 'Monospace Parchment',
    badge: 'PAPER-INK',
    bg: 'bg-[#f4efe4]',
    bgSecondary: 'bg-[#eae3d2]',
    text: 'text-neutral-900',
    textMuted: 'text-neutral-500',
    textBright: 'text-black',
    border: 'border-neutral-300',
    borderActive: 'border-neutral-800',
    accent: 'text-amber-800',
    accentBg: 'bg-amber-100',
    verseNum: 'text-amber-900 font-bold',
    bloomClass: '',
    cursorColor: 'bg-neutral-900',
    promptUser: 'text-amber-900',
    promptHost: 'text-neutral-600',
  },
  dracula: {
    id: 'dracula',
    name: 'Dracula Shell',
    badge: 'DRACULA',
    bg: 'bg-[#1b1c24]',
    bgSecondary: 'bg-[#282a36]',
    text: 'text-[#f8f8f2]',
    textMuted: 'text-[#6272a4]',
    textBright: 'text-[#50fa7b]',
    border: 'border-[#44475a]',
    borderActive: 'border-[#bd93f9]',
    accent: 'text-[#bd93f9]',
    accentBg: 'bg-[#44475a]/50',
    verseNum: 'text-[#ff79c6] font-bold',
    bloomClass: '',
    cursorColor: 'bg-[#50fa7b]',
    promptUser: 'text-[#bd93f9]',
    promptHost: 'text-[#6272a4]',
  },
  solarized: {
    id: 'solarized',
    name: 'Solarized Dark',
    badge: 'SOLARIZED',
    bg: 'bg-[#00212b]',
    bgSecondary: 'bg-[#073642]',
    text: 'text-[#839496]',
    textMuted: 'text-[#586e75]',
    textBright: 'text-[#93a1a1]',
    border: 'border-[#073642]',
    borderActive: 'border-[#2aa198]',
    accent: 'text-[#2aa198]',
    accentBg: 'bg-[#073642]/80',
    verseNum: 'text-[#b58900] font-bold',
    bloomClass: '',
    cursorColor: 'bg-[#2aa198]',
    promptUser: 'text-[#268bd2]',
    promptHost: 'text-[#586e75]',
  }
};
